<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AttributesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('attributes')->delete();
        
        \DB::table('attributes')->insert(array (
            0 => 
            array (
                'id' => 2,
                'name' => 'description',
                'alterlabels' => '{"cs": "Popis", "en": "Description", "ru": "Описание"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "rich_editor", "rules": ["string"], "has_label": true, "section_id": "1", "column_span": "4", "column_start": "1", "order_number": "3"}',
                'filter_layout' => '{"type": "hidden"}',
                'show_layout' => '{"type": "rich_editor", "has_label": false, "section_id": "22", "order_number": "1"}',
                'group_layout' => '{"group_id": "3", "order_number": "1"}',
                'is_translatable' => 1,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-05-21 17:33:41',
                'updated_at' => '2024-11-26 14:25:15',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 4,
                'name' => 'current_price',
                'alterlabels' => '{"cs": "Cena", "en": "Price", "ru": "Стоимость"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "price", "has_label": true, "section_id": "49", "column_span": "3", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "between", "has_label": true, "section_id": "2", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "price", "has_label": true, "section_id": "50", "order_number": "1"}',
                'group_layout' => '{"group_id": "1", "order_number": "1"}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 1,
                'is_active' => 1,
                'created_at' => '2024-05-21 17:39:42',
                'updated_at' => '2024-11-26 21:43:57',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 5,
                'name' => 'note_on_price',
                'alterlabels' => '{"cs": "Poznámka k ceně", "en": "Note on price", "ru": "Пометка к цене"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "text_input", "rules": ["string"], "has_label": true, "section_id": "49", "column_span": "3", "column_start": "1", "order_number": "3"}',
                'filter_layout' => '{"type": "hidden"}',
                'show_layout' => '{"type": "text_input", "has_label": true, "section_id": "50", "order_number": "3"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 1,
                'is_feature' => 1,
                'is_required' => 0,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-05-21 17:44:16',
                'updated_at' => '2024-11-26 21:44:54',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 6,
                'name' => 'real_estate_deposit',
                'alterlabels' => '{"cs": "Kauce", "en": "Deposit", "ru": "Залог"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => '[{"value": "5", "attribute_name": "real_estate_type"}, {"value": "78", "attribute_name": "real_estate_type"}]',
                'hidden' => '[{"value": "4", "attribute_name": "real_estate_type"}]',
                'create_layout' => '{"type": "price", "has_label": true, "section_id": "49", "column_span": "3", "column_start": "1", "order_number": "4"}',
                'filter_layout' => '{"type": "between", "has_label": true, "section_id": "2", "column_span": "4", "column_start": "1", "order_number": "4"}',
                'show_layout' => '{"type": "price", "has_label": true, "section_id": "50", "order_number": "4"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-05-21 17:46:53',
                'updated_at' => '2024-11-26 21:45:23',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 7,
                'name' => 'real_estate_type',
                'alterlabels' => '{"cs": "Typ", "en": "Type", "ru": "Тип"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "1", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "33", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "5", "order_number": "1"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-05-21 17:49:37',
                'updated_at' => '2024-11-26 15:04:43',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 8,
                'name' => 'real_estate_configuration',
                'alterlabels' => '{"cs": "Konfigurace", "en": "Configuration", "ru": "Конфигурация"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "has_label": true, "section_id": "32", "column_span": "2", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "checkbox_list", "has_label": true, "section_id": "33", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "select", "has_label": true, "section_id": "5", "order_number": "1"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-05-21 18:31:00',
                'updated_at' => '2024-11-26 21:46:30',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 9,
                'name' => 'building',
                'alterlabels' => '{"cs": "Budova", "en": "Building", "ru": "Здание"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "has_label": true, "section_id": "4", "column_span": "2", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "checkbox_list", "has_label": true, "section_id": "27", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "select", "has_label": true, "section_id": "28", "order_number": "1"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-05-21 18:41:59',
                'updated_at' => '2024-11-26 14:51:27',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 10,
                'name' => 'condition',
                'alterlabels' => '{"cs": "Stav", "en": "Condition", "ru": "Состояние"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '{"cs": null, "en": null, "ru": null}',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "has_label": true, "section_id": "4", "column_span": "2", "column_start": "3", "order_number": "2"}',
                'filter_layout' => '{"type": "checkbox_list", "has_label": true, "section_id": "27", "column_span": "4", "column_start": "1", "order_number": "2"}',
                'show_layout' => '{"type": "select", "has_label": true, "section_id": "28", "order_number": "2"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-05-21 18:45:41',
                'updated_at' => '2024-11-26 14:51:53',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 11,
                'name' => 'number_of_floors',
                'alterlabels' => '{"cs": "Počet podlaží", "en": "Number of floors", "ru": "Количество этажей"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '{"cs": "podlaží", "en": "flors", "ru": "этажей"}',
                'visible' => '[]',
                'hidden' => '[]',
                'create_layout' => '{"type": "text_input", "rules": ["numeric"], "has_label": true, "section_id": "4", "column_span": "2", "column_start": "1", "order_number": "3"}',
                'filter_layout' => '{"type": "between", "has_label": true, "section_id": "27", "column_span": "4", "column_start": "1", "order_number": "3"}',
                'show_layout' => '{"type": "text_input", "has_label": true, "section_id": "28", "order_number": "3"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-05-21 18:47:28',
                'updated_at' => '2024-11-26 14:55:30',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 12,
                'name' => 'number_of_underground_floors',
                'alterlabels' => '{"cs": "Počet podzemních podlaží", "en": "Number of underground floors", "ru": "Количество подземных этажей"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '{"cs": "podlaží", "en": "floors", "ru": "этажей"}',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "text_input", "rules": ["numeric"], "has_label": true, "section_id": "4", "column_span": "2", "column_start": "3", "order_number": "4"}',
                'filter_layout' => '{"type": "between", "has_label": true, "section_id": "27", "column_span": "4", "column_start": "1", "order_number": "4"}',
                'show_layout' => '{"type": "text_input", "has_label": true, "section_id": "28", "order_number": "4"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-05-21 18:48:21',
                'updated_at' => '2024-11-26 14:55:45',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 13,
                'name' => 'elevator',
                'alterlabels' => '{"cs": "Výtah", "en": "Elevator", "ru": "Лифт"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "4", "column_span": "2", "column_start": "1", "order_number": "5"}',
                'filter_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "27", "column_span": "4", "column_start": "1", "order_number": "5"}',
                'show_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "28", "order_number": "5"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-05-21 18:50:35',
                'updated_at' => '2024-11-26 14:56:02',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 14,
                'name' => 'balcony',
                'alterlabels' => '{"cs": "Balkon", "en": "Balcony", "ru": "Балкон"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "5", "column_span": "2", "column_start": "1", "order_number": "4"}',
                'filter_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "5", "column_span": "4", "column_start": "1", "order_number": "4"}',
                'show_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "5", "order_number": "4"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-05-21 18:51:39',
                'updated_at' => '2024-11-26 13:43:39',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 15,
                'name' => 'parking',
                'alterlabels' => '{"cs": "Parkoviště", "en": "Parking", "ru": "Паркинг"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "4", "column_span": "2", "column_start": "1", "order_number": "6"}',
                'filter_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "27", "column_span": "4", "column_start": "1", "order_number": "6"}',
                'show_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "28", "order_number": "6"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-05-21 18:53:35',
                'updated_at' => '2024-11-26 14:56:15',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 16,
                'name' => 'square',
                'alterlabels' => '{"cs": "Plocha", "en": "Square", "ru": "Площадь"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '{"en": "m²"}',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "text_input", "rules": ["numeric"], "has_label": true, "section_id": "32", "column_span": "2", "column_start": "3", "order_number": "2"}',
                'filter_layout' => '{"type": "between", "has_label": true, "section_id": "33", "column_span": "4", "column_start": "1", "order_number": "2"}',
                'show_layout' => '{"type": "text_input", "has_label": true, "section_id": "5", "order_number": "2"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-05-22 11:11:59',
                'updated_at' => '2024-11-26 14:56:49',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 21,
                'name' => 'salary_type',
                'alterlabels' => '{"cs": "Typ platby", "en": "Salary type", "ru": "Тип оплаты"}',
                'alterprefixes' => '{"cs": "/", "en": "/", "ru": "/"}',
                'altersuffixes' => '[]',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "has_label": true, "section_id": "60", "column_span": "3", "column_start": "1", "order_number": "3"}',
                'filter_layout' => '{"type": "toggle_buttons", "has_label": false, "section_id": "35", "column_span": "4", "column_start": "1", "order_number": "3"}',
                'show_layout' => '{"type": "select", "has_label": false, "section_id": "23", "order_number": "3"}',
                'group_layout' => '{"group_id": "1", "order_number": "3"}',
                'is_translatable' => 0,
                'is_feature' => 0,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-05-24 16:48:19',
                'updated_at' => '2024-12-03 12:22:15',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 22,
                'name' => 'phone_ram',
            'alterlabels' => '{"cs": "RAM (operační paměť)", "en": "RAM (operating memory)", "ru": "RAM (оперативная память)"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "has_label": true, "section_id": "47", "column_span": "2", "column_start": "3", "order_number": "2"}',
                'filter_layout' => '{"type": "checkbox_list", "has_label": true, "section_id": "8", "column_span": "4", "column_start": "1", "order_number": "2"}',
                'show_layout' => '{"type": "select", "has_label": true, "section_id": "48", "order_number": "2"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 0,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-05-25 14:58:39',
                'updated_at' => '2024-11-26 21:40:31',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 23,
                'name' => 'phone_rom',
            'alterlabels' => '{"cs": "ROM (zabudovaná paměť)", "en": "ROM (integrated memory)", "ru": "ROM (встроенная память)"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "has_label": true, "section_id": "47", "column_span": "2", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "checkbox_list", "has_label": true, "section_id": "8", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "select", "has_label": true, "section_id": "48", "order_number": "1"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 0,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-05-25 15:08:54',
                'updated_at' => '2024-11-26 21:40:15',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 24,
                'name' => 'phone_display_diagonal',
                'alterlabels' => '{"cs": "Úhlopříčka displeje", "en": "Display diagonal", "ru": "Диагональ дисплея"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '{"cs": null, "en": "\\"", "ru": null}',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "has_label": true, "section_id": "45", "column_span": "2", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "checkbox_list", "has_label": true, "section_id": "9", "column_span": "2", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "select", "has_label": true, "section_id": "46", "order_number": "1"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 0,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-05-25 15:15:31',
                'updated_at' => '2024-11-26 21:24:59',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 25,
                'name' => 'phone_display_type',
                'alterlabels' => '{"cs": "Typ displeje ", "en": "Display type", "ru": "Тип дисплея"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '{"cs": null, "en": null, "ru": null}',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "has_label": true, "section_id": "45", "column_span": "2", "column_start": "3", "order_number": "2"}',
                'filter_layout' => '{"type": "checkbox_list", "has_label": true, "section_id": "9", "column_span": "2", "column_start": "3", "order_number": "2"}',
                'show_layout' => '{"type": "select", "has_label": true, "section_id": "46", "order_number": "2"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 0,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-05-25 15:17:15',
                'updated_at' => '2024-11-26 21:24:39',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 27,
                'name' => 'geo_id',
                'alterlabels' => '{"cs": "Lokace", "en": "Location", "ru": "Расположение"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '{"cs": null, "en": null, "ru": null}',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "location", "has_label": true, "section_id": "36", "column_span": "3", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "hidden"}',
                'show_layout' => '{"type": "location", "has_label": false, "section_id": "23", "order_number": "0"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 0,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-05-28 09:01:30',
                'updated_at' => '2024-11-26 21:36:44',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 28,
                'name' => 'salary',
                'alterlabels' => '{"cs": "Plat", "en": "Salary", "ru": "Зарплата"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '{"cs": null, "en": null, "ru": null}',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "price_from_to", "has_label": true, "section_id": "60", "column_span": "3", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "price_from_to", "has_label": true, "section_id": "35", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "price_from_to", "has_label": true, "section_id": "23", "order_number": "1"}',
                'group_layout' => '{"group_id": "1", "order_number": "1"}',
                'is_translatable' => 0,
                'is_feature' => 0,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-06-03 13:54:15',
                'updated_at' => '2024-12-07 14:12:41',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 29,
                'name' => 'address',
                'alterlabels' => '{"cs": "Adresa", "en": "Address", "ru": "Адрес"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "text_input", "rules": ["string"], "has_label": true, "section_id": "36", "column_span": "3", "column_start": "1", "order_number": "2"}',
                'filter_layout' => '{"type": "hidden"}',
                'show_layout' => '{"type": "text_input", "has_label": true, "section_id": "40", "order_number": "2"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-06-16 13:22:55',
                'updated_at' => '2024-11-26 15:03:13',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 30,
                'name' => 'type_of_object',
                'alterlabels' => '{"cs": "Typ objektu", "en": "Type of object", "ru": "Вид объекта"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "has_label": true, "section_id": "32", "column_span": "2", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "checkbox_list", "has_label": true, "section_id": "33", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "select", "has_label": true, "section_id": "5", "order_number": "1"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-07-15 12:31:43',
                'updated_at' => '2024-11-26 14:58:45',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 31,
                'name' => 'number_of_rooms',
                'alterlabels' => '{"cs": "Počet pokojů", "en": "Number of rooms", "ru": "Количество комнат"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '{"cs": null, "en": null, "ru": null}',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "has_label": true, "section_id": "32", "column_span": "2", "column_start": "1", "order_number": "3"}',
                'filter_layout' => '{"type": "checkbox_list", "has_label": true, "section_id": "33", "column_span": "2", "column_start": "1", "order_number": "3"}',
                'show_layout' => '{"type": "select", "has_label": true, "section_id": "5", "order_number": "3"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-07-15 12:36:20',
                'updated_at' => '2024-11-26 14:57:44',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 32,
                'name' => 'title',
                'alterlabels' => '{"cs": "Název", "en": "Title", "ru": "Заголовок"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "text_input", "rules": ["string"], "has_label": true, "section_id": "1", "column_span": "4", "column_start": "1", "order_number": "2"}',
                'filter_layout' => '{"type": "hidden"}',
                'show_layout' => '{"type": "text_input", "has_label": false, "section_id": "23", "order_number": "1"}',
                'group_layout' => '{"group_id": "2", "order_number": "1"}',
                'is_translatable' => 1,
                'is_feature' => 0,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-07-17 10:42:21',
                'updated_at' => '2024-12-01 20:34:54',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 33,
                'name' => 'type_of_housing',
                'alterlabels' => '{"cs": "Typ ubytování", "en": "Type of housing", "ru": "Тип жилья"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "has_label": true, "section_id": "32", "column_span": "2", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "33", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "select", "has_label": true, "section_id": "5", "order_number": "1"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-07-17 11:32:19',
                'updated_at' => '2024-11-26 15:00:05',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 34,
                'name' => 'type_of_object_garage',
                'alterlabels' => '{"cs": "Typ objektu", "en": "Type of object", "ru": "Тип объекта"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "has_label": true, "section_id": "32", "column_span": "2", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "33", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "select", "has_label": true, "section_id": "5", "order_number": "1"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-07-17 11:43:59',
                'updated_at' => '2024-11-26 15:00:44',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 35,
                'name' => 'type_of_object_commercial',
                'alterlabels' => '{"cs": "Typ objektu", "en": "Type of object", "ru": "Тип объекта"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "has_label": true, "section_id": "32", "column_span": "2", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "checkbox_list", "has_label": true, "section_id": "33", "column_span": "2", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "select", "has_label": true, "section_id": "5", "order_number": "1"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-07-17 12:22:20',
                'updated_at' => '2024-11-26 15:01:19',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 36,
                'name' => 'land_category',
                'alterlabels' => '{"cs": "Kategorie pozemků", "en": "Land category", "ru": "Категория земли"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "has_label": true, "section_id": "32", "column_span": "2", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "checkbox_list", "has_label": true, "section_id": "33", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "select", "has_label": true, "section_id": "5", "order_number": "1"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-07-17 13:00:03',
                'updated_at' => '2024-11-26 15:01:46',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 37,
                'name' => 'lessor',
                'alterlabels' => '{"cs": "Pronajímatel", "en": "Lessor", "ru": "Арендодатель"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => '[{"value": "5", "attribute_name": "real_estate_type"}, {"value": "78", "attribute_name": "real_estate_type"}]',
                'hidden' => NULL,
                'create_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "49", "column_span": "2", "column_start": "1", "order_number": "5"}',
                'filter_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "2", "column_span": "4", "column_start": "1", "order_number": "5"}',
                'show_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "50", "order_number": "5"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-07-17 13:06:54',
                'updated_at' => '2024-11-26 21:45:51',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 38,
                'name' => 'agency_fee',
                'alterlabels' => '{"cs": "Poplatek realitní kanceláři", "en": "Agency fee", "ru": "Гонорар агентству"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => '[{"value": "98", "attribute_name": "lessor"}]',
                'hidden' => '[{"value": "97", "attribute_name": "lessor"}]',
                'create_layout' => '{"type": "price", "has_label": true, "section_id": "49", "column_span": "3", "column_start": "1", "order_number": "6"}',
                'filter_layout' => '{"type": "hidden"}',
                'show_layout' => '{"type": "price", "has_label": true, "section_id": "50", "order_number": "6"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-07-17 13:11:31',
                'updated_at' => '2024-11-26 21:46:09',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 41,
                'name' => 'currency',
                'alterlabels' => '{"cs": "Měna", "en": "Currency", "ru": "Валюта"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "has_label": true, "section_id": "49", "column_span": "1", "column_start": "4", "order_number": "2"}',
                'filter_layout' => '{"type": "hidden"}',
                'show_layout' => '{"type": "select", "has_label": true, "section_id": "50", "order_number": "2"}',
                'group_layout' => '{"group_id": "1", "order_number": "2"}',
                'is_translatable' => 0,
                'is_feature' => 0,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-08-10 11:38:44',
                'updated_at' => '2024-11-26 21:44:18',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 42,
                'name' => 'job_currency',
                'alterlabels' => '{"cs": "Měna", "en": "Currency", "ru": "Валюта"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "has_label": true, "section_id": "21", "column_span": "1", "column_start": "4", "order_number": "2"}',
                'filter_layout' => '{"type": "hidden"}',
                'show_layout' => '{"type": "select", "has_label": false, "section_id": "23", "order_number": "2"}',
                'group_layout' => '{"group_id": "1", "order_number": "2"}',
                'is_translatable' => 0,
                'is_feature' => 0,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-08-10 18:07:00',
                'updated_at' => '2024-11-26 22:41:27',
                'deleted_at' => '2024-11-26 22:41:27',
            ),
            33 => 
            array (
                'id' => 43,
                'name' => 'mileage',
                'alterlabels' => '{"cs": "Počet ujetých kilometrů", "en": "Mileage", "ru": "Пробег"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '{"cs": "km", "en": "km", "ru": "km"}',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "between", "rules": ["numeric"], "has_label": true, "section_id": "53", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "between", "has_label": true, "section_id": 14, "column_span": "4", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "between", "has_label": true, "section_id": "54", "order_number": "1"}',
                'group_layout' => '{"group_id": "2", "order_number": "3"}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-08-17 15:55:44',
                'updated_at' => '2024-12-07 13:55:17',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 44,
                'name' => 'manufacturer',
                'alterlabels' => '{"cs": "Výrobce", "en": "Manufacturer", "ru": "Производитель"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "has_label": true, "section_id": "55", "column_span": "2", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "select", "has_label": true, "section_id": 15, "column_span": "4", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "select", "has_label": true, "section_id": "56", "order_number": "1"}',
                'group_layout' => '{"group_id": "2", "order_number": "1"}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-08-17 16:12:07',
                'updated_at' => '2024-11-26 22:54:13',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 45,
                'name' => 'bmv_model',
                'alterlabels' => '{"cs": "Model", "en": "Model", "ru": "Модель"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => '[{"value": "118", "attribute_name": "manufacturer"}]',
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "has_label": true, "section_id": "55", "column_span": "2", "column_start": "3", "order_number": "2"}',
                'filter_layout' => '{"type": "multiple_select", "has_label": true, "section_id": "15", "column_span": "4", "column_start": "1", "order_number": "2"}',
                'show_layout' => '{"type": "select", "has_label": true, "section_id": "56", "order_number": "2"}',
                'group_layout' => '{"group_id": "2", "order_number": "2"}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-08-17 16:20:14',
                'updated_at' => '2024-11-26 22:54:32',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 46,
                'name' => 'honda_model',
                'alterlabels' => '{"cs": "Model", "en": "Model", "ru": "Модель"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => '[{"value": "119", "attribute_name": "manufacturer"}]',
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "has_label": true, "section_id": "55", "column_span": "2", "column_start": "3", "order_number": "2"}',
                'filter_layout' => '{"type": "multiple_select", "has_label": true, "section_id": "15", "column_span": "2", "column_start": "3", "order_number": "2"}',
                'show_layout' => '{"type": "select", "has_label": true, "section_id": "56", "order_number": "2"}',
                'group_layout' => '{"group_id": "2", "order_number": "3"}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-08-17 16:43:28',
                'updated_at' => '2024-11-26 22:54:51',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 47,
                'name' => 'the_year_of_issue',
                'alterlabels' => '{"cs": "Rok výroby", "en": "The year of issue", "ru": "Год выпуска"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "month_year", "has_label": true, "section_id": "55", "column_span": "4", "column_start": "1", "order_number": "3"}',
                'filter_layout' => '{"type": "month_year", "has_label": true, "section_id": "15", "column_span": "4", "column_start": "1", "order_number": "3"}',
                'show_layout' => '{"type": "month_year", "has_label": true, "section_id": "56", "order_number": "3"}',
                'group_layout' => '{"group_id": "2", "order_number": "3"}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-08-17 18:15:09',
                'updated_at' => '2024-12-07 13:55:00',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 48,
                'name' => 'body_type',
                'alterlabels' => '{"cs": "Typ karosérie", "en": "Body type", "ru": "Тип кузова"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "has_label": true, "section_id": "55", "column_span": "4", "column_start": "1", "order_number": "4"}',
                'filter_layout' => '{"type": "checkbox_list", "has_label": true, "section_id": "15", "column_span": "4", "column_start": "1", "order_number": "4"}',
                'show_layout' => '{"type": "select", "has_label": true, "section_id": "56", "order_number": "4"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-08-18 11:01:28',
                'updated_at' => '2024-11-26 22:55:31',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 49,
                'name' => 'count_of_doors',
                'alterlabels' => '{"cs": "Počet dveří", "en": "Count of doors", "ru": "Количество дверей"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "has_label": true, "section_id": "55", "column_span": "2", "column_start": "1", "order_number": "5"}',
                'filter_layout' => '{"type": "select", "has_label": true, "section_id": "15", "column_span": "2", "column_start": "1", "order_number": "5"}',
                'show_layout' => '{"type": "select", "has_label": true, "section_id": "56", "order_number": "5"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-08-18 11:07:34',
                'updated_at' => '2024-11-26 22:55:52',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 50,
                'name' => 'number_of_seats',
                'alterlabels' => '{"cs": "Počet míst", "en": "Number of seats", "ru": "Количество мест"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "has_label": true, "section_id": "55", "column_span": "2", "column_start": "3", "order_number": "6"}',
                'filter_layout' => '{"type": "select", "has_label": true, "section_id": "15", "column_span": "2", "column_start": "3", "order_number": "6"}',
                'show_layout' => '{"type": "select", "has_label": true, "section_id": "56", "order_number": "6"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-08-18 11:10:01',
                'updated_at' => '2024-11-26 22:56:11',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 51,
                'name' => 'fuel_type',
                'alterlabels' => '{"cs": "Typ paliva", "en": "Fuel type", "ru": "Тип топлива"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "has_label": false, "section_id": "43", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "select", "has_label": false, "section_id": "16", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "select", "has_label": false, "section_id": "44", "order_number": "1"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-08-18 11:23:34',
                'updated_at' => '2024-11-26 21:18:57',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 52,
                'name' => 'engine_displacement',
                'alterlabels' => '{"cs": "Objem motoru", "en": "Engine displacement", "ru": "Объем двигателя"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "text_input", "rules": ["numeric"], "has_label": true, "section_id": "43", "column_span": "4", "column_start": "1", "order_number": "2"}',
                'filter_layout' => '{"type": "between", "has_label": true, "section_id": "16", "column_span": "4", "column_start": "1", "order_number": "2"}',
                'show_layout' => '{"type": "text_input", "has_label": true, "section_id": "44", "order_number": "2"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-08-18 11:25:46',
                'updated_at' => '2024-11-26 21:19:50',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 53,
                'name' => 'motor_power',
                'alterlabels' => '{"cs": "Výkon motoru", "en": "Motor power", "ru": "Мощность двигателя"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "text_input", "rules": ["numeric"], "has_label": true, "section_id": "43", "column_span": "4", "column_start": "1", "order_number": "3"}',
                'filter_layout' => '{"type": "between", "has_label": true, "section_id": "16", "column_span": "4", "column_start": "1", "order_number": "3"}',
                'show_layout' => '{"type": "text_input", "has_label": true, "section_id": "44", "order_number": "3"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-08-18 11:40:42',
                'updated_at' => '2024-11-26 21:20:51',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 54,
                'name' => 'approximate_fuel_consumption',
                'alterlabels' => '{"cs": "Přibližná spotřeba", "en": "Approximate fuel consumption", "ru": "Приблизительный расход топлива"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '{"cs": null, "en": "l/100km", "ru": null}',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "text_input", "rules": ["numeric"], "has_label": true, "section_id": "43", "column_span": "4", "column_start": "1", "order_number": "4"}',
                'filter_layout' => '{"type": "between", "has_label": true, "section_id": "16", "column_span": "4", "column_start": "1", "order_number": "4"}',
                'show_layout' => '{"type": "text_input", "has_label": true, "section_id": "44", "order_number": "4"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 0,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-08-18 11:46:08',
                'updated_at' => '2024-11-26 21:20:23',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 55,
                'name' => 'transmission_type',
                'alterlabels' => '{"cs": "Typ převodovky", "en": "Transmission type", "ru": "Тип коробки передач"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "has_label": true, "section_id": "51", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "select", "has_label": true, "section_id": "17", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "select", "has_label": true, "section_id": "52", "order_number": "1"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-08-19 09:23:58',
                'updated_at' => '2024-11-26 22:51:02',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 56,
                'name' => 'number_of_transmissions',
                'alterlabels' => '{"cs": "Počet rychlostí", "en": "Number of transmissions", "ru": "Количество передач"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "has_label": true, "section_id": "51", "column_span": "2", "column_start": "1", "order_number": "2"}',
                'filter_layout' => '{"type": "select", "has_label": true, "section_id": "17", "column_span": "4", "column_start": "1", "order_number": "2"}',
                'show_layout' => '{"type": "select", "has_label": true, "section_id": "52", "order_number": "2"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-08-19 09:32:31',
                'updated_at' => '2024-11-26 22:51:26',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 57,
                'name' => 'drive',
                'alterlabels' => '{"cs": "Pohon", "en": "Drive", "ru": "Привод"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "has_label": true, "section_id": "51", "column_span": "2", "column_start": "3", "order_number": "3"}',
                'filter_layout' => '{"type": "select", "has_label": true, "section_id": "17", "column_span": "4", "column_start": "1", "order_number": "3"}',
                'show_layout' => '{"type": "select", "has_label": true, "section_id": "52", "order_number": "3"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-08-19 09:49:47',
                'updated_at' => '2024-11-26 22:53:09',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 58,
                'name' => 'created_at',
                'alterlabels' => '{"cs": "CreatedAt", "en": "CreatedAt", "ru": "CreatedAt"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "hidden", "has_label": false, "section_id": "24", "column_span": "1", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "created_at", "has_label": false, "section_id": "25", "column_span": "1", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "hidden"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 1,
                'is_active' => 1,
                'created_at' => '2024-10-10 16:38:45',
                'updated_at' => '2024-11-26 14:42:45',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 59,
                'name' => 'proposed_salary',
                'alterlabels' => '{"cs": "Navrhovaná mzda", "en": "Proposed salary", "ru": "Предлагаемая оплата"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "price", "has_label": true, "section_id": "60", "column_span": "3", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "between", "has_label": true, "section_id": "35", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "price", "has_label": true, "section_id": "34", "order_number": "1"}',
                'group_layout' => '{"group_id": "1", "order_number": "1"}',
                'is_translatable' => 0,
                'is_feature' => 0,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 0,
                'created_at' => '2024-11-24 15:55:15',
                'updated_at' => '2024-12-07 13:26:56',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 60,
                'name' => 'type_of_employment',
                'alterlabels' => '{"cs": "Typ zaměstnání", "en": "Type of employment", "ru": "Тип занятости"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "has_label": true, "section_id": "21", "column_span": "3", "column_start": "1", "order_number": "5"}',
                'filter_layout' => '{"type": "checkbox_list", "has_label": true, "section_id": "35", "column_span": "4", "column_start": "1", "order_number": "5"}',
                'show_layout' => '{"type": "select", "has_label": true, "section_id": "34", "order_number": "5"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-11-25 17:51:43',
                'updated_at' => '2024-12-01 21:10:20',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 61,
                'name' => 'work_experience',
                'alterlabels' => '{"cs": "Pracovní zkušenosti", "en": "Work experience", "ru": "Опыт работы"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "38", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "39", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "19", "order_number": "1"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-11-25 18:12:04',
                'updated_at' => '2024-11-26 14:47:50',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 62,
                'name' => 'education',
                'alterlabels' => '{"cs": "Vzdělávání", "en": "Education", "ru": "Образование"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "38", "column_span": "4", "column_start": "1", "order_number": "2"}',
                'filter_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "39", "column_span": "4", "column_start": "1", "order_number": "2"}',
                'show_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "19", "order_number": "2"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-11-25 18:33:10',
                'updated_at' => '2024-12-01 22:24:16',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 63,
                'name' => 'work_schedule',
                'alterlabels' => '{"cs": "Pracovní plán", "en": "Work schedule", "ru": "График работы"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "has_label": true, "section_id": "21", "column_span": "3", "column_start": "1", "order_number": "6"}',
                'filter_layout' => '{"type": "checkbox_list", "has_label": true, "section_id": "35", "column_span": "4", "column_start": "1", "order_number": "6"}',
                'show_layout' => '{"type": "select", "has_label": true, "section_id": "34", "order_number": "6"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-11-25 20:35:02',
                'updated_at' => '2024-12-01 20:49:48',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 64,
                'name' => 'payment_frequency',
                'alterlabels' => '{"cs": "Četnost plateb", "en": "Payment frequency", "ru": "Частота выплат"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "has_label": true, "section_id": "60", "column_span": "3", "column_start": "1", "order_number": "4"}',
                'filter_layout' => '{"type": "checkbox_list", "has_label": true, "section_id": "35", "column_span": "4", "column_start": "1", "order_number": "4"}',
                'show_layout' => '{"type": "select", "has_label": true, "section_id": "34", "order_number": "4"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-11-25 20:51:17',
                'updated_at' => '2024-12-03 12:22:23',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 65,
                'name' => 'drivers_license',
                'alterlabels' => '{"cs": "Řidičský průkaz", "en": "Driver\'s license", "ru": "Водительское удостоверение"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "has_label": true, "section_id": "38", "column_span": "3", "column_start": "1", "order_number": "3"}',
                'filter_layout' => '{"type": "single_multiple_select", "has_label": true, "section_id": "39", "column_span": "4", "column_start": "1", "order_number": "3"}',
                'show_layout' => '{"type": "select", "has_label": true, "section_id": "19", "order_number": "3"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-11-26 12:21:13',
                'updated_at' => '2024-12-08 15:32:13',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 66,
                'name' => 'additional_requirements',
                'alterlabels' => '{"cs": "Další požadavky", "en": "Additional requirements", "ru": "Дополнительные требования"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "markdown_editor", "rules": ["string"], "has_label": true, "section_id": "38", "column_span": "4", "column_start": "1", "order_number": "4"}',
                'filter_layout' => '{"type": "hidden"}',
                'show_layout' => '{"type": "markdown_editor", "has_label": true, "section_id": "19", "order_number": "4"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 1,
                'is_feature' => 1,
                'is_required' => 0,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-12-01 20:40:41',
                'updated_at' => '2024-12-01 20:44:27',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 67,
                'name' => 'housing',
                'alterlabels' => '{"cs": "Bydlení", "en": "Housing", "ru": "Жилье"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "57", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "58", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "59", "order_number": "1"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-12-01 21:20:29',
                'updated_at' => '2024-12-01 21:20:35',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 68,
                'name' => 'housing',
                'alterlabels' => '{"cs": "Bydlení", "en": "Housing", "ru": "Жилье"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "57", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "58", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "59", "order_number": "1"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-12-01 21:22:03',
                'updated_at' => '2024-12-01 21:23:56',
                'deleted_at' => '2024-12-01 21:23:56',
            ),
            59 => 
            array (
                'id' => 69,
                'name' => 'vehicle',
                'alterlabels' => '{"cs": "Vozidlo", "en": "Vehicle", "ru": "Транспортное средство"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "57", "column_span": "4", "column_start": "1", "order_number": "2"}',
                'filter_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "58", "column_span": "4", "column_start": "1", "order_number": "2"}',
                'show_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "59", "order_number": "2"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-12-01 21:26:14',
                'updated_at' => '2024-12-01 21:45:58',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 70,
                'name' => 'health_insurance',
                'alterlabels' => '{"cs": "Zdravotní pojištění", "en": "Health insurance", "ru": "Медицинская страховка"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "57", "column_span": "4", "column_start": "1", "order_number": "3"}',
                'filter_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "58", "column_span": "4", "column_start": "1", "order_number": "3"}',
                'show_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "59", "order_number": "3"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-12-01 22:27:12',
                'updated_at' => '2024-12-03 12:07:03',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 71,
                'name' => 'training',
                'alterlabels' => '{"cs": "Školení", "en": "Training", "ru": "Обучение"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "57", "column_span": "4", "column_start": "1", "order_number": "4"}',
                'filter_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "58", "column_span": "4", "column_start": "1", "order_number": "4"}',
                'show_layout' => '{"type": "toggle_buttons", "has_label": true, "section_id": "59", "order_number": "4"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-12-03 12:10:01',
                'updated_at' => '2024-12-03 12:10:43',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 72,
                'name' => 'employment_relationship',
                'alterlabels' => '{"cs": "Pracovní vztahy", "en": "Employment relationship", "ru": "Трудовые отношения"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "has_label": true, "section_id": "21", "column_span": "3", "column_start": "1", "order_number": "4"}',
                'filter_layout' => '{"type": "checkbox_list", "has_label": true, "section_id": "35", "column_span": "3", "column_start": "1", "order_number": "4"}',
                'show_layout' => '{"type": "select", "has_label": true, "section_id": "34", "order_number": "5"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-12-03 13:57:02',
                'updated_at' => '2024-12-03 14:00:30',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 73,
                'name' => 'scope_of_work',
                'alterlabels' => '{"cs": "Rozsah práce", "en": "Scope of work", "ru": "Сфера деятельности"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "has_label": true, "section_id": "1", "column_span": "3", "column_start": "1", "order_number": "3"}',
                'filter_layout' => '{"type": "multiple_select", "has_label": true, "section_id": "41", "column_span": "4", "column_start": "1", "order_number": "3"}',
                'show_layout' => '{"type": "select", "has_label": true, "section_id": "34", "order_number": "1"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 1,
                'is_active' => 1,
                'created_at' => '2024-12-07 17:54:53',
                'updated_at' => '2024-12-07 18:35:21',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 74,
                'name' => 'knowledge_of_languages',
                'alterlabels' => '{"cs": "Znalost jazyků", "en": "Knowledge of languages", "ru": "Знание языков"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "multiple_select", "has_label": true, "section_id": "1", "column_span": "3", "column_start": "1", "order_number": "4"}',
                'filter_layout' => '{"type": "multiple_select", "has_label": true, "section_id": "41", "column_span": "3", "column_start": "1", "order_number": "4"}',
                'show_layout' => '{"type": "multiple_select", "has_label": true, "section_id": "42", "order_number": "4"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_active' => 1,
                'created_at' => '2024-12-08 13:53:08',
                'updated_at' => '2024-12-08 16:09:25',
                'deleted_at' => '2024-12-08 16:09:25',
            ),
        ));
        
        
    }
}