<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AttributesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('attributes')->delete();
        
        \DB::table('attributes')->insert(array (
            0 => 
            array (
                'id' => 2,
                'name' => 'description',
                'alterlabels' => '{"cz": "Popis", "en": "Description", "ru": "Описание"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '[]',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "markdown_editor", "rules": ["string"], "section_id": "1", "column_span": "4", "column_start": "1", "order_number": "3"}',
                'filter_layout' => '{"type": "hidden"}',
                'show_layout' => '{"type": "markdown_editor", "section_id": "1", "order_number": "1"}',
                'group_layout' => '{"group_id": "3", "order_number": "1"}',
                'default' => NULL,
                'is_translatable' => 1,
                'is_feature' => 0,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-05-21 17:33:41',
                'updated_at' => '2024-10-07 22:32:57',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 4,
                'name' => 'current_price',
                'alterlabels' => '{"cz": "Cena", "en": "Price", "ru": "Стоимость"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '[]',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "price", "section_id": "2", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "between", "section_id": "2", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "price", "section_id": "2", "order_number": "1"}',
                'group_layout' => '{"group_id": "1", "order_number": "1"}',
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 0,
                'is_required' => 1,
                'is_always_required' => 1,
                'is_readonly' => 0,
                'is_sortable' => 1,
                'created_at' => '2024-05-21 17:39:42',
                'updated_at' => '2024-10-29 12:40:44',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 5,
                'name' => 'note_on_price',
                'alterlabels' => '{"cz": "Poznámka k ceně", "en": "Note on price", "ru": "Пометка к цене"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '[]',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "text_input", "section_id": "2", "column_span": "3", "column_start": "1", "order_number": "3"}',
                'filter_layout' => '{"type": "hidden"}',
                'show_layout' => '{"type": "text_input", "section_id": "2", "order_number": "3"}',
                'group_layout' => NULL,
                'default' => NULL,
                'is_translatable' => 1,
                'is_feature' => 1,
                'is_required' => 0,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-05-21 17:44:16',
                'updated_at' => '2024-08-11 13:46:23',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 6,
                'name' => 'real_estate_deposit',
                'alterlabels' => '{"cz": "Kauce", "en": "Deposit", "ru": "Залог"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '[]',
                'visible' => '[{"value": "5", "attribute_name": "real_estate_type"}, {"value": "78", "attribute_name": "real_estate_type"}]',
                'hidden' => '[{"value": "4", "attribute_name": "real_estate_type"}]',
                'create_layout' => '{"type": "price", "section_id": "2", "column_span": "3", "column_start": "1", "order_number": "4"}',
                'filter_layout' => '{"type": "between", "section_id": "2", "column_span": "4", "column_start": "1", "order_number": "4"}',
                'show_layout' => '{"type": "price", "section_id": "2", "order_number": "4"}',
                'group_layout' => NULL,
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-05-21 17:46:53',
                'updated_at' => '2024-08-14 10:08:37',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 7,
                'name' => 'real_estate_type',
                'alterlabels' => '{"cz": "Typ", "en": "Type", "ru": "Тип"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '[]',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "toggle_buttons", "section_id": "1", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "toggle_buttons", "section_id": "1", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "toggle_buttons", "section_id": "13", "order_number": "1"}',
                'group_layout' => NULL,
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-05-21 17:49:37',
                'updated_at' => '2024-08-11 13:42:37',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 8,
                'name' => 'real_estate_configuration',
                'alterlabels' => '{"cz": "Konfigurace", "en": "Configuration", "ru": "Конфигурация"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '[]',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "section_id": "5", "column_span": "2", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "checkbox_list", "section_id": "5", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "select", "section_id": "5", "order_number": "1"}',
                'group_layout' => NULL,
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-05-21 18:31:00',
                'updated_at' => '2024-08-26 21:57:15',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 9,
                'name' => 'building',
                'alterlabels' => '{"cs": "Budova", "en": "Building", "ru": "Здание"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '{"cs": null, "en": null}',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "section_id": "4", "column_span": "2", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "checkbox_list", "section_id": "4", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "select", "section_id": "4", "order_number": "1"}',
                'group_layout' => NULL,
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-05-21 18:41:59',
                'updated_at' => '2024-08-14 09:44:21',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 10,
                'name' => 'condition',
                'alterlabels' => '{"cs": "Stav", "en": "Condition", "ru": "Состояние"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '[]',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "section_id": "4", "column_span": "2", "column_start": "3", "order_number": "2"}',
                'filter_layout' => '{"type": "checkbox_list", "section_id": "4", "column_span": "4", "column_start": "1", "order_number": "2"}',
                'show_layout' => '{"type": "select", "section_id": "4", "order_number": "2"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-05-21 18:45:41',
                'updated_at' => '2024-10-16 11:25:19',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 11,
                'name' => 'number_of_floors',
                'alterlabels' => '{"cs": "Počet podlaží", "en": "Number of floors", "ru": "Количество этажей"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '{"cs": "podlaží", "en": "flors", "ru": "этажей"}',
                'visible' => '[]',
                'hidden' => '[]',
                'create_layout' => '{"type": "text_input", "rules": ["numeric"], "section_id": "4", "column_span": "2", "column_start": "1", "order_number": "3"}',
                'filter_layout' => '{"type": "between", "section_id": "4", "column_span": "4", "column_start": "1", "order_number": "3"}',
                'show_layout' => '{"type": "text_input", "section_id": "4", "order_number": "3"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-05-21 18:47:28',
                'updated_at' => '2024-10-16 11:25:42',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 12,
                'name' => 'number_of_underground_floors',
                'alterlabels' => '{"cz": "Počet podzemních podlaží", "en": "Number of underground floors", "ru": "Количество подземных этажей"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '{"cz": "podlaží", "en": "floors", "ru": "этажей"}',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "text_input", "rules": ["numeric"], "section_id": "4", "column_span": "2", "column_start": "3", "order_number": "4"}',
                'filter_layout' => '{"type": "between", "section_id": "4", "column_span": "4", "column_start": "1", "order_number": "4"}',
                'show_layout' => '{"type": "text_input", "section_id": "4", "order_number": "4"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-05-21 18:48:21',
                'updated_at' => '2024-10-16 11:26:04',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 13,
                'name' => 'elevator',
                'alterlabels' => '{"cz": "Výtah", "en": "Elevator", "ru": "Лифт"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '[]',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "toggle_buttons", "section_id": "4", "column_span": "2", "column_start": "1", "order_number": "5"}',
                'filter_layout' => '{"type": "toggle_buttons", "section_id": "4", "column_span": "4", "column_start": "1", "order_number": "5"}',
                'show_layout' => '{"type": "toggle_buttons", "section_id": "4", "order_number": "5"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-05-21 18:50:35',
                'updated_at' => '2024-10-16 11:26:45',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 14,
                'name' => 'balcony',
                'alterlabels' => '{"cz": "Balkon", "en": "Balcony", "ru": "Балкон"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '[]',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "toggle_buttons", "section_id": "5", "column_span": "2", "column_start": "1", "order_number": "4"}',
                'filter_layout' => '{"type": "toggle_buttons", "section_id": "5", "column_span": "4", "column_start": "1", "order_number": "4"}',
                'show_layout' => '{"type": "toggle_buttons", "section_id": "5", "order_number": "4"}',
                'group_layout' => NULL,
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-05-21 18:51:39',
                'updated_at' => '2024-08-26 21:59:24',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 15,
                'name' => 'parking',
                'alterlabels' => '{"cz": "Parkoviště", "en": "Parking", "ru": "Паркинг"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '[]',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "toggle_buttons", "section_id": "4", "column_span": "2", "column_start": "1", "order_number": "6"}',
                'filter_layout' => '{"type": "toggle_buttons", "section_id": "4", "column_span": "4", "column_start": "1", "order_number": "6"}',
                'show_layout' => '{"type": "toggle_buttons", "section_id": "4", "order_number": "6"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-05-21 18:53:35',
                'updated_at' => '2024-10-16 11:27:06',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 16,
                'name' => 'square',
                'alterlabels' => '{"cz": "Plocha", "en": "Square", "ru": "Площадь"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '{"en": "m²"}',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "text_input", "rules": ["numeric"], "section_id": "5", "column_span": "2", "column_start": "3", "order_number": "2"}',
                'filter_layout' => '{"type": "between", "section_id": "5", "column_span": "4", "column_start": "1", "order_number": "2"}',
                'show_layout' => '{"type": "text_input", "section_id": "5", "order_number": "2"}',
                'group_layout' => NULL,
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-05-22 11:11:59',
                'updated_at' => '2024-08-26 21:58:23',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 21,
                'name' => 'salary_type',
                'alterlabels' => '{"cz": "Typ platby", "en": "Salary type", "ru": "Тип оплаты"}',
                'alterprefixes' => '{"cs": "/", "en": "/", "ru": "/"}',
                'altersuffixes' => '[]',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "section_id": "7", "column_span": "1", "column_start": "1", "order_number": "4"}',
                'filter_layout' => '{"type": "checkbox_list", "section_id": "7", "column_span": "4", "column_start": "1", "order_number": "4"}',
                'show_layout' => '{"type": "select", "section_id": "7", "order_number": "4"}',
                'group_layout' => '{"group_id": "1", "order_number": "3"}',
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 0,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-05-24 16:48:19',
                'updated_at' => '2024-10-29 15:27:09',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 22,
                'name' => 'phone_ram',
            'alterlabels' => '{"cz": "RAM (operační paměť)", "en": "RAM (operating memory)", "ru": "RAM (оперативная память)"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "section_id": "8", "column_span": "1", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "checkbox_list", "section_id": "8", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "select", "section_id": "8", "order_number": "1"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 0,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-05-25 14:58:39',
                'updated_at' => '2024-10-31 13:55:59',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 23,
                'name' => 'phone_rom',
            'alterlabels' => '{"cz": "ROM (zabudovaná paměť)", "en": "ROM (integrated memory)", "ru": "ROM (встроенная память)"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "section_id": "8", "column_span": "1", "column_start": "2", "order_number": "2"}',
                'filter_layout' => '{"type": "checkbox_list", "section_id": "8", "column_span": "4", "column_start": "1", "order_number": "2"}',
                'show_layout' => '{"type": "select", "section_id": "8", "order_number": "2"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 0,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-05-25 15:08:54',
                'updated_at' => '2024-10-31 13:56:51',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 24,
                'name' => 'display_diagonal',
                'alterlabels' => '{"cz": "Úhlopříčka displeje", "en": "Display diagonal", "ru": "Диагональ дисплея"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '{"cz": null, "en": "\\"", "ru": null}',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "section_id": "9", "column_span": "2", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "checkbox_list", "section_id": "9", "column_span": "2", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "select", "section_id": "9", "order_number": "1"}',
                'group_layout' => NULL,
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 0,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-05-25 15:15:31',
                'updated_at' => '2024-08-11 13:33:50',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 25,
                'name' => 'display_type',
                'alterlabels' => '{"cz": "Typ displeje ", "en": "Display type", "ru": "Тип дисплея"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '{"cz": null, "en": null, "ru": null}',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "section_id": "9", "column_span": "2", "column_start": "3", "order_number": "2"}',
                'filter_layout' => '{"type": "checkbox_list", "section_id": "9", "column_span": "2", "column_start": "3", "order_number": "2"}',
                'show_layout' => '{"type": "select", "section_id": "9", "order_number": "2"}',
                'group_layout' => NULL,
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 0,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-05-25 15:17:15',
                'updated_at' => '2024-08-11 13:34:16',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 27,
                'name' => 'geo_id',
                'alterlabels' => '{"cz": "Lokace", "en": "Location", "ru": "Расположение"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '{"cz": null, "en": null, "ru": null}',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "location", "section_id": "10", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "hidden"}',
                'show_layout' => '{"type": "location", "section_id": "10", "order_number": "1"}',
                'group_layout' => NULL,
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 0,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-05-28 09:01:30',
                'updated_at' => '2024-09-17 16:05:46',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 28,
                'name' => 'salary',
                'alterlabels' => '{"cz": "Mzda", "en": "Salary", "ru": "Зарплата"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '{"cz": null, "en": null, "ru": null}',
                'visible' => '[]',
                'hidden' => NULL,
                'create_layout' => '{"type": "from_to", "rules": ["numeric"], "section_id": "7", "column_span": "3", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "from_to", "section_id": "7", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "from_to", "section_id": "2", "order_number": "1"}',
                'group_layout' => '{"group_id": "1", "order_number": "1"}',
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 0,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-06-03 13:54:15',
                'updated_at' => '2024-10-29 15:27:39',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 29,
                'name' => 'address',
                'alterlabels' => '{"cs": "Adresa", "en": "Address", "ru": "Адрес"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "text_input", "rules": ["string"], "section_id": "10", "column_span": "3", "column_start": "1", "order_number": "2"}',
                'filter_layout' => '{"type": "hidden"}',
                'show_layout' => '{"type": "text_input", "section_id": "10", "order_number": "2"}',
                'group_layout' => NULL,
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-06-16 13:22:55',
                'updated_at' => '2024-08-17 15:12:01',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 30,
                'name' => 'type_of_object',
                'alterlabels' => '{"cs": "Typ objektu", "en": "Type of object", "ru": "Вид объекта"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "section_id": "5", "column_span": "2", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "checkbox_list", "section_id": "5", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "select", "section_id": "5", "order_number": "1"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-07-15 12:31:43',
                'updated_at' => '2024-10-29 15:30:24',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 31,
                'name' => 'number_of_rooms',
                'alterlabels' => '{"cs": "Počet pokojů", "en": "Number of rooms", "ru": "Количество комнат"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '{"cs": null, "en": null, "ru": null}',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "section_id": "5", "column_span": "2", "column_start": "1", "order_number": "3"}',
                'filter_layout' => '{"type": "checkbox_list", "section_id": "5", "column_span": "2", "column_start": "1", "order_number": "3"}',
                'show_layout' => '{"type": "select", "section_id": "5", "order_number": "3"}',
                'group_layout' => NULL,
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-07-15 12:36:20',
                'updated_at' => '2024-08-11 13:40:54',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 32,
                'name' => 'title',
                'alterlabels' => '{"cs": "Název", "en": "Title", "ru": "Заголовок"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "text_input", "rules": ["string"], "section_id": "1", "column_span": "4", "column_start": "1", "order_number": "2"}',
                'filter_layout' => '{"type": "hidden"}',
                'show_layout' => '{"type": "text_input", "section_id": "1", "order_number": "1"}',
                'group_layout' => '{"group_id": "2", "order_number": "1"}',
                'default' => NULL,
                'is_translatable' => 1,
                'is_feature' => 0,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-07-17 10:42:21',
                'updated_at' => '2024-10-07 22:13:34',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 33,
                'name' => 'type_of_housing',
                'alterlabels' => '{"cs": "Typ ubytování", "en": "Type of housing", "ru": "Тип жилья"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "section_id": "5", "column_span": "2", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "toggle_buttons", "section_id": "5", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "select", "section_id": "5", "order_number": "1"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-07-17 11:32:19',
                'updated_at' => '2024-10-29 15:31:12',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 34,
                'name' => 'type_of_object_garage',
                'alterlabels' => '{"cs": "Typ objektu", "en": "Type of object", "ru": "Тип объекта"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "section_id": "5", "column_span": "2", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "toggle_buttons", "section_id": "5", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "select", "section_id": "5", "order_number": "1"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-07-17 11:43:59',
                'updated_at' => '2024-10-29 15:30:14',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 35,
                'name' => 'type_of_object_commercial',
                'alterlabels' => '{"cs": "Typ objektu", "en": "Type of object", "ru": "Тип объекта"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "section_id": "5", "column_span": "2", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "checkbox_list", "section_id": "5", "column_span": "2", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "select", "section_id": "5", "order_number": "1"}',
                'group_layout' => NULL,
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-07-17 12:22:20',
                'updated_at' => '2024-08-11 13:38:59',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 36,
                'name' => 'land_category',
                'alterlabels' => '{"cs": "Kategorie pozemků", "en": "Land category", "ru": "Категория земли"}',
                'alterprefixes' => '[]',
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "section_id": "5", "column_span": "2", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "checkbox_list", "section_id": "5", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "select", "section_id": "5", "order_number": "1"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-07-17 13:00:03',
                'updated_at' => '2024-10-29 15:30:45',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 37,
                'name' => 'lessor',
                'alterlabels' => '{"cs": "Pronajímatel", "en": "Lessor", "ru": "Арендодатель"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '[]',
                'visible' => '[{"value": "5", "attribute_name": "real_estate_type"}, {"value": "78", "attribute_name": "real_estate_type"}]',
                'hidden' => NULL,
                'create_layout' => '{"type": "toggle_buttons", "section_id": "2", "column_span": "2", "column_start": "1", "order_number": "5"}',
                'filter_layout' => '{"type": "toggle_buttons", "section_id": "2", "column_span": "4", "column_start": "1", "order_number": "5"}',
                'show_layout' => '{"type": "toggle_buttons", "section_id": "2", "order_number": "5"}',
                'group_layout' => NULL,
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-07-17 13:06:54',
                'updated_at' => '2024-08-11 13:35:41',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 38,
                'name' => 'agency_fee',
                'alterlabels' => '{"cs": "Poplatek realitní kanceláři", "en": "Agency fee", "ru": "Гонорар агентству"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '[]',
                'visible' => '[{"value": "98", "attribute_name": "lessor"}]',
                'hidden' => '[{"value": "97", "attribute_name": "lessor"}]',
                'create_layout' => '{"type": "price", "section_id": "2", "column_span": "3", "column_start": "1", "order_number": "6"}',
                'filter_layout' => '{"type": "hidden"}',
                'show_layout' => '{"type": "price", "section_id": "2", "order_number": "6"}',
                'group_layout' => NULL,
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-07-17 13:11:31',
                'updated_at' => '2024-08-14 10:11:47',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 41,
                'name' => 'currency',
                'alterlabels' => '{"cs": "Měna", "en": "Currency", "ru": "Валюта"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "section_id": "2", "column_span": "1", "column_start": "4", "order_number": "2"}',
                'filter_layout' => '{"type": "hidden"}',
                'show_layout' => '{"type": "select", "section_id": "2", "order_number": "2"}',
                'group_layout' => '{"group_id": "1", "order_number": "2"}',
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 0,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-08-10 11:38:44',
                'updated_at' => '2024-10-29 12:41:22',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 42,
                'name' => 'job_currency',
                'alterlabels' => '{"cs": "Měna", "en": "Currency", "ru": "Валюта"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "section_id": "7", "column_span": "1", "column_start": "4", "order_number": "2"}',
                'filter_layout' => '{"type": "hidden"}',
                'show_layout' => '{"type": "select", "section_id": "12", "order_number": "2"}',
                'group_layout' => '{"group_id": "1", "order_number": "2"}',
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 0,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-08-10 18:07:00',
                'updated_at' => '2024-10-29 14:29:56',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 43,
                'name' => 'mileage',
                'alterlabels' => '{"cs": "Počet ujetých kilometrů", "en": "Mileage", "ru": "Пробег"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '{"cs": "km", "en": "km", "ru": "km"}',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "between", "rules": ["numeric"], "section_id": "14", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "between", "section_id": 14, "column_span": "4", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "between", "section_id": "14", "order_number": "1"}',
                'group_layout' => '{"group_id": "2", "order_number": "3"}',
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 1,
                'created_at' => '2024-08-17 15:55:44',
                'updated_at' => '2024-10-07 22:07:44',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 44,
                'name' => 'manufacturer',
                'alterlabels' => '{"cs": "Výrobce", "en": "Manufacturer", "ru": "Производитель"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "section_id": "15", "column_span": "2", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "select", "section_id": 15, "column_span": "4", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "select", "section_id": "15", "order_number": "1"}',
                'group_layout' => '{"group_id": "2", "order_number": "1"}',
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-08-17 16:12:07',
                'updated_at' => '2024-10-07 21:54:27',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 45,
                'name' => 'bmv_model',
                'alterlabels' => '{"cs": "Model", "en": "Model", "ru": "Модель"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '[]',
                'visible' => '[{"value": "118", "attribute_name": "manufacturer"}]',
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "section_id": "15", "column_span": "2", "column_start": "3", "order_number": "2"}',
                'filter_layout' => '{"type": "multiple_select", "section_id": "15", "column_span": "4", "column_start": "1", "order_number": "2"}',
                'show_layout' => '{"type": "select", "section_id": "15", "order_number": "2"}',
                'group_layout' => '{"group_id": "2", "order_number": "2"}',
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-08-17 16:20:14',
                'updated_at' => '2024-10-07 21:54:22',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 46,
                'name' => 'honda_model',
                'alterlabels' => '{"cs": "Model", "en": "Model", "ru": "Модель"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '[]',
                'visible' => '[{"value": "119", "attribute_name": "manufacturer"}]',
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "section_id": "15", "column_span": "2", "column_start": "3", "order_number": "2"}',
                'filter_layout' => '{"type": "multiple_select", "section_id": "15", "column_span": "2", "column_start": "3", "order_number": "2"}',
                'show_layout' => '{"type": "select", "section_id": "15", "order_number": "2"}',
                'group_layout' => '{"group_id": "2", "order_number": "3"}',
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-08-17 16:43:28',
                'updated_at' => '2024-10-07 22:19:11',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 47,
                'name' => 'the_year_of_issue',
                'alterlabels' => '{"cs": "Rok výroby", "en": "The year of issue", "ru": "Год выпуска"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "month_year", "section_id": "15", "column_span": "4", "column_start": "1", "order_number": "3"}',
                'filter_layout' => '{"type": "month_year", "section_id": "15", "column_span": "4", "column_start": "1", "order_number": "3"}',
                'show_layout' => '{"type": "month_year", "section_id": "15", "order_number": "3"}',
                'group_layout' => '{"group_id": "2", "order_number": "3"}',
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 1,
                'created_at' => '2024-08-17 18:15:09',
                'updated_at' => '2024-10-07 22:03:20',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 48,
                'name' => 'body_type',
                'alterlabels' => '{"cs": "Typ karosérie", "en": "Body type", "ru": "Тип кузова"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "section_id": "15", "column_span": "4", "column_start": "1", "order_number": "4"}',
                'filter_layout' => '{"type": "checkbox_list", "section_id": "15", "column_span": "4", "column_start": "1", "order_number": "4"}',
                'show_layout' => '{"type": "select", "section_id": "15", "order_number": "4"}',
                'group_layout' => NULL,
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-08-18 11:01:28',
                'updated_at' => '2024-08-18 11:02:13',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 49,
                'name' => 'count_of_doors',
                'alterlabels' => '{"cs": "Počet dveří", "en": "Count of doors", "ru": "Количество дверей"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "section_id": "15", "column_span": "2", "column_start": "1", "order_number": "5"}',
                'filter_layout' => '{"type": "select", "section_id": "15", "column_span": "2", "column_start": "1", "order_number": "5"}',
                'show_layout' => '{"type": "select", "section_id": "15", "order_number": "5"}',
                'group_layout' => NULL,
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-08-18 11:07:34',
                'updated_at' => '2024-08-18 11:07:34',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 50,
                'name' => 'number_of_seats',
                'alterlabels' => '{"cs": "Počet míst", "en": "Number of seats", "ru": "Количество мест"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "section_id": "15", "column_span": "2", "column_start": "3", "order_number": "6"}',
                'filter_layout' => '{"type": "select", "section_id": "15", "column_span": "2", "column_start": "3", "order_number": "6"}',
                'show_layout' => '{"type": "select", "section_id": "15", "order_number": "6"}',
                'group_layout' => NULL,
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-08-18 11:10:01',
                'updated_at' => '2024-08-18 11:10:01',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 51,
                'name' => 'fuel_type',
                'alterlabels' => '{"cs": "Typ paliva", "en": "Fuel type", "ru": "Тип топлива"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "section_id": "16", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "select", "section_id": 16, "column_span": "4", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "select", "section_id": "16", "order_number": "1"}',
                'group_layout' => NULL,
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-08-18 11:23:34',
                'updated_at' => '2024-08-18 11:23:34',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 52,
                'name' => 'engine_displacement',
                'alterlabels' => '{"cs": "Objem motoru", "en": "Engine displacement", "ru": "Объем двигателя"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "between", "rules": ["numeric"], "section_id": "16", "column_span": "4", "column_start": "1", "order_number": "2"}',
                'filter_layout' => '{"type": "between", "section_id": "16", "column_span": "4", "column_start": "1", "order_number": "2"}',
                'show_layout' => '{"type": "between", "section_id": "16", "order_number": "2"}',
                'group_layout' => NULL,
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-08-18 11:25:46',
                'updated_at' => '2024-08-18 11:25:46',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 53,
                'name' => 'motor_power',
                'alterlabels' => '{"cs": "Výkon motoru", "en": "Motor power", "ru": "Мощность двигателя"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "between", "rules": ["numeric"], "section_id": "16", "column_span": "4", "column_start": "1", "order_number": "3"}',
                'filter_layout' => '{"type": "between", "section_id": "16", "column_span": "4", "column_start": "1", "order_number": "3"}',
                'show_layout' => '{"type": "between", "section_id": "16", "order_number": "3"}',
                'group_layout' => NULL,
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-08-18 11:40:42',
                'updated_at' => '2024-08-18 11:40:42',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 54,
                'name' => 'approximate_fuel_consumption',
                'alterlabels' => '{"cs": "Přibližná spotřeba", "en": "Approximate fuel consumption", "ru": "Приблизительный расход топлива"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '{"cs": null, "en": "l/100km", "ru": null}',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "between", "rules": ["numeric"], "section_id": "16", "column_span": "4", "column_start": "1", "order_number": "4"}',
                'filter_layout' => '{"type": "between", "section_id": "16", "column_span": "4", "column_start": "1", "order_number": "4"}',
                'show_layout' => '{"type": "between", "section_id": "16", "order_number": "4"}',
                'group_layout' => NULL,
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 0,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-08-18 11:46:08',
                'updated_at' => '2024-08-18 11:46:08',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 55,
                'name' => 'transmission_type',
                'alterlabels' => '{"cs": "Typ převodovky", "en": "Transmission type", "ru": "Тип коробки передач"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "section_id": "17", "column_span": "4", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "select", "section_id": 17, "column_span": "4", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "select", "section_id": "17", "order_number": "1"}',
                'group_layout' => NULL,
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-08-19 09:23:58',
                'updated_at' => '2024-08-19 09:40:52',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 56,
                'name' => 'number_of_transmissions',
                'alterlabels' => '{"cs": "Počet rychlostí", "en": "Number of transmissions", "ru": "Количество передач"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "section_id": "17", "column_span": "2", "column_start": "1", "order_number": "2"}',
                'filter_layout' => '{"type": "select", "section_id": "17", "column_span": "4", "column_start": "1", "order_number": "2"}',
                'show_layout' => '{"type": "select", "section_id": "17", "order_number": "2"}',
                'group_layout' => NULL,
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-08-19 09:32:31',
                'updated_at' => '2024-08-19 09:53:52',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 57,
                'name' => 'drive',
                'alterlabels' => '{"cs": "Pohon", "en": "Drive", "ru": "Привод"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "select", "section_id": "17", "column_span": "2", "column_start": "3", "order_number": "3"}',
                'filter_layout' => '{"type": "select", "section_id": "17", "column_span": "4", "column_start": "1", "order_number": "3"}',
                'show_layout' => '{"type": "select", "section_id": "17", "order_number": "3"}',
                'group_layout' => NULL,
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 1,
                'is_required' => 1,
                'is_always_required' => 0,
                'is_readonly' => 0,
                'is_sortable' => 0,
                'created_at' => '2024-08-19 09:49:47',
                'updated_at' => '2024-10-07 12:18:51',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 58,
                'name' => 'created_at',
                'alterlabels' => '{"cs": "CreatedAt", "en": "CreatedAt", "ru": "CreatedAt"}',
                'alterprefixes' => NULL,
                'altersuffixes' => '[]',
                'visible' => NULL,
                'hidden' => NULL,
                'create_layout' => '{"type": "created_at", "section_id": "18", "column_span": "1", "column_start": "1", "order_number": "1"}',
                'filter_layout' => '{"type": "created_at", "section_id": "18", "column_span": "1", "column_start": "1", "order_number": "1"}',
                'show_layout' => '{"type": "created_at", "section_id": "18", "order_number": "1"}',
                'group_layout' => '{"group_id": null, "order_number": null}',
                'default' => NULL,
                'is_translatable' => 0,
                'is_feature' => 0,
                'is_required' => 1,
                'is_always_required' => 1,
                'is_readonly' => 0,
                'is_sortable' => 1,
                'created_at' => '2024-10-10 16:38:45',
                'updated_at' => '2024-10-17 14:21:48',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}