<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MediaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('media')->delete();
        
        \DB::table('media')->insert(array (
            0 => 
            array (
                'id' => 1,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 1,
                'uuid' => '217fd19f-83d7-4a55-8fe7-628311efdf54',
                'collection_name' => 'categories',
                'name' => '01J5C6C7ZA106E42237PQ6HM5K',
                'file_name' => '01JBCHF7AZG5KGXNDWWHYMKKQF.png',
                'mime_type' => 'image/png',
                'disk' => 'aws_categories',
                'conversions_disk' => 'aws_categories',
                'size' => 288592,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-10-29 16:24:16',
                'updated_at' => '2024-10-29 16:24:20',
            ),
            1 => 
            array (
                'id' => 2,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 3,
                'uuid' => 'ae259b42-d878-49b9-b79c-e6666c6ad6a7',
                'collection_name' => 'categories',
                'name' => '01J0GTQGGWYW71S48V826Q3BCN',
                'file_name' => '01JBCHFPRN1AHR8D5EP27Y929G.png',
                'mime_type' => 'image/png',
                'disk' => 'aws_categories',
                'conversions_disk' => 'aws_categories',
                'size' => 49271,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-10-29 16:24:32',
                'updated_at' => '2024-10-29 16:24:35',
            ),
            2 => 
            array (
                'id' => 3,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 4,
                'uuid' => '7ec1d85e-1be3-40bc-946c-efaf61dd59c3',
                'collection_name' => 'categories',
                'name' => '01J2RHFD851RWX4CSEH2MMFRFK',
                'file_name' => '01JBCHG0YXSVH56485B139EZSY.png',
                'mime_type' => 'image/png',
                'disk' => 'aws_categories',
                'conversions_disk' => 'aws_categories',
                'size' => 7627,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-10-29 16:24:42',
                'updated_at' => '2024-10-29 16:24:44',
            ),
            3 => 
            array (
                'id' => 4,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 9,
                'uuid' => 'b11222fd-adee-4940-8663-8a5d3be10453',
                'collection_name' => 'categories',
                'name' => '01J2RHBVFC38D4XVJ4N6VXHX4T',
                'file_name' => '01JBCHG9PNWR5RP8Q3YDCJ11HP.png',
                'mime_type' => 'image/png',
                'disk' => 'aws_categories',
                'conversions_disk' => 'aws_categories',
                'size' => 34384,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-10-29 16:24:51',
                'updated_at' => '2024-10-29 16:24:54',
            ),
            4 => 
            array (
                'id' => 5,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 10,
                'uuid' => '84bc88f5-bd4c-474d-b48f-bf8e96fa2a5d',
                'collection_name' => 'categories',
                'name' => '01J2RH9BE3Q0CPJRY1RJ7TY8YB',
                'file_name' => '01JBCHGS510ZAJ2MX5KTKX4MR9.png',
                'mime_type' => 'image/png',
                'disk' => 'aws_categories',
                'conversions_disk' => 'aws_categories',
                'size' => 27003,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-10-29 16:25:07',
                'updated_at' => '2024-10-29 16:25:09',
            ),
            5 => 
            array (
                'id' => 6,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 11,
                'uuid' => '6774c007-79a6-47a4-9c8d-044c841c8f9a',
                'collection_name' => 'categories',
                'name' => '01J2RJ99PQWSX2T159D2E8T2PN',
                'file_name' => '01JBCHH2WZ1BZYNDE85HW1FPHA.png',
                'mime_type' => 'image/png',
                'disk' => 'aws_categories',
                'conversions_disk' => 'aws_categories',
                'size' => 94509,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-10-29 16:25:17',
                'updated_at' => '2024-10-29 16:25:19',
            ),
            6 => 
            array (
                'id' => 7,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 12,
                'uuid' => 'dfcddf79-82ca-41a3-bb88-8cc933e8a2a6',
                'collection_name' => 'categories',
                'name' => '01J2RJKNAPRGDR9403TWYG67E0',
                'file_name' => '01JBCHHDEJ1VAV5WVD9HF6E1QS.png',
                'mime_type' => 'image/png',
                'disk' => 'aws_categories',
                'conversions_disk' => 'aws_categories',
                'size' => 26578,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-10-29 16:25:28',
                'updated_at' => '2024-10-29 16:25:31',
            ),
            7 => 
            array (
                'id' => 8,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 13,
                'uuid' => '7d51677c-9e8f-4ba6-ace1-d46631869189',
                'collection_name' => 'categories',
                'name' => '01J2RJQVTYZCXK1HW2XVCME1JG',
                'file_name' => '01JBCHHQYC3F1MZGQR26X9EK4H.png',
                'mime_type' => 'image/png',
                'disk' => 'aws_categories',
                'conversions_disk' => 'aws_categories',
                'size' => 56308,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-10-29 16:25:39',
                'updated_at' => '2024-10-29 16:25:40',
            ),
            8 => 
            array (
                'id' => 9,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 14,
                'uuid' => '0cbed6e3-2e04-49b2-9ef8-950570286e41',
                'collection_name' => 'categories',
                'name' => '01J2RKYKB8EG7QN7F8Z0N8GMYE',
                'file_name' => '01JBCHJ1RFJSHTJDQAVGBTV3AB.png',
                'mime_type' => 'image/png',
                'disk' => 'aws_categories',
                'conversions_disk' => 'aws_categories',
                'size' => 40955,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-10-29 16:25:49',
                'updated_at' => '2024-10-29 16:25:50',
            ),
            9 => 
            array (
                'id' => 10,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 15,
                'uuid' => '4600bffb-ed35-4d18-8a31-b057b33e2a0e',
                'collection_name' => 'categories',
                'name' => '01J2RN65E9GC4YZKN0QQ7K1E8Y',
                'file_name' => '01JBCHJF3ZS0F07MHQ1EEPHK5R.png',
                'mime_type' => 'image/png',
                'disk' => 'aws_categories',
                'conversions_disk' => 'aws_categories',
                'size' => 57635,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-10-29 16:26:02',
                'updated_at' => '2024-10-29 16:26:05',
            ),
            10 => 
            array (
                'id' => 11,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 16,
                'uuid' => '862adf25-1f57-4557-b02e-0c7f435d5b03',
                'collection_name' => 'categories',
                'name' => '01J2RNDX8CWYVYHVAXZA35CGM5',
                'file_name' => '01JBCHJTGH4Y66YXMF6V8X42R1.png',
                'mime_type' => 'image/png',
                'disk' => 'aws_categories',
                'conversions_disk' => 'aws_categories',
                'size' => 42212,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-10-29 16:26:14',
                'updated_at' => '2024-10-29 16:26:15',
            ),
            11 => 
            array (
                'id' => 12,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 17,
                'uuid' => '3e5bf1b5-e013-487b-ad07-ca6a0ca7a124',
                'collection_name' => 'categories',
                'name' => '01J2RNGW94VX4JRSBX83EA1HDB',
                'file_name' => '01JBCHK70SY5P9MPEKJEG91HTR.png',
                'mime_type' => 'image/png',
                'disk' => 'aws_categories',
                'conversions_disk' => 'aws_categories',
                'size' => 51733,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-10-29 16:26:27',
                'updated_at' => '2024-10-29 16:26:30',
            ),
            12 => 
            array (
                'id' => 13,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 2,
                'uuid' => '22fadd00-6dca-4edf-a474-29b37f72a8a1',
                'collection_name' => 'categories',
                'name' => '01J0H1CJMFJEX6J5VKARXXKG94',
                'file_name' => '01JBCHM8BGNDGDF2WDGPAWRN83.png',
                'mime_type' => 'image/png',
                'disk' => 'aws_categories',
                'conversions_disk' => 'aws_categories',
                'size' => 28382,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-10-29 16:27:01',
                'updated_at' => '2024-10-29 16:27:04',
            ),
            13 => 
            array (
                'id' => 14,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 18,
                'uuid' => 'e3d52071-0f88-4270-859d-dd70644aba42',
                'collection_name' => 'categories',
                'name' => '01J2RNSAJ8KGVZYF3C6G70TXTS',
                'file_name' => '01JBCHMJJ1HJQ87P0YJY7G2XNE.png',
                'mime_type' => 'image/png',
                'disk' => 'aws_categories',
                'conversions_disk' => 'aws_categories',
                'size' => 59157,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-10-29 16:27:11',
                'updated_at' => '2024-10-29 16:27:13',
            ),
            14 => 
            array (
                'id' => 15,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 19,
                'uuid' => '97879a5b-2235-4259-9639-fd5a22d685c4',
                'collection_name' => 'categories',
                'name' => '01J2RQ2N8CC86T6BK4038JHAEX',
                'file_name' => '01JBCHMVZ108TQB02RN4CFW99Y.png',
                'mime_type' => 'image/png',
                'disk' => 'aws_categories',
                'conversions_disk' => 'aws_categories',
                'size' => 14007,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-10-29 16:27:21',
                'updated_at' => '2024-10-29 16:27:22',
            ),
            15 => 
            array (
                'id' => 16,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 20,
                'uuid' => '93f9966e-ea6a-48d3-a7bc-1142d33f4c06',
                'collection_name' => 'categories',
                'name' => '01J2RQ7EY0QHPDX7QABGCRRVG3',
                'file_name' => '01JBCHN68HJSR70ZM7JKMF6FQQ.png',
                'mime_type' => 'image/png',
                'disk' => 'aws_categories',
                'conversions_disk' => 'aws_categories',
                'size' => 28573,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-10-29 16:27:31',
                'updated_at' => '2024-10-29 16:27:35',
            ),
            16 => 
            array (
                'id' => 17,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 21,
                'uuid' => '892731a2-6550-4db3-8c59-2fa5111b278f',
                'collection_name' => 'categories',
                'name' => '01J2RQC369NWHVHCKGZFHPZVTS',
                'file_name' => '01JBCHNKDK7RZC0SWVC5DXPW7P.png',
                'mime_type' => 'image/png',
                'disk' => 'aws_categories',
                'conversions_disk' => 'aws_categories',
                'size' => 20827,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-10-29 16:27:45',
                'updated_at' => '2024-10-29 16:27:47',
            ),
            17 => 
            array (
                'id' => 18,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 22,
                'uuid' => '55bb7fdb-4ff9-41ac-951b-138bae53702b',
                'collection_name' => 'categories',
                'name' => '01J2RQWJREMSCN4J29AQA5VAGE',
                'file_name' => '01JBCHNXZZYX109PFE1SHRYJGC.png',
                'mime_type' => 'image/png',
                'disk' => 'aws_categories',
                'conversions_disk' => 'aws_categories',
                'size' => 32834,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-10-29 16:27:56',
                'updated_at' => '2024-10-29 16:27:56',
            ),
            18 => 
            array (
                'id' => 19,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 5,
                'uuid' => '459ddcf3-e076-4c0a-8c19-0d048886045a',
                'collection_name' => 'categories',
                'name' => '01J2RHFD851RWX4CSEH2MMFRFK',
                'file_name' => '01JBCHWMCQZW8BRT6JV6T6ESEX.png',
                'mime_type' => 'image/png',
                'disk' => 'aws_categories',
                'conversions_disk' => 'aws_categories',
                'size' => 7627,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-10-29 16:31:35',
                'updated_at' => '2024-10-29 16:31:36',
            ),
            19 => 
            array (
                'id' => 20,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 23,
                'uuid' => '0cb68bac-6e61-4d03-980d-80721c2b9bc5',
                'collection_name' => 'categories',
                'name' => '01J2RRTFV5YWAVNS244P356A6W',
                'file_name' => '01JBCHWZ3X5F52M8CGTYPF9NBB.png',
                'mime_type' => 'image/png',
                'disk' => 'aws_categories',
                'conversions_disk' => 'aws_categories',
                'size' => 47055,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-10-29 16:31:46',
                'updated_at' => '2024-10-29 16:31:48',
            ),
            20 => 
            array (
                'id' => 21,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 24,
                'uuid' => 'bdb2e4b7-64d6-4268-8e32-f52c705cae12',
                'collection_name' => 'categories',
                'name' => '01J2RRZWT3023EW2YSRAN5FDS6',
                'file_name' => '01JBCHXJ7EWQK6M8TZ73RT21XF.png',
                'mime_type' => 'image/png',
                'disk' => 'aws_categories',
                'conversions_disk' => 'aws_categories',
                'size' => 55450,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-10-29 16:32:06',
                'updated_at' => '2024-10-29 16:32:07',
            ),
            21 => 
            array (
                'id' => 22,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 25,
                'uuid' => 'f89fcda8-0de4-4693-b7b2-24ff579f3676',
                'collection_name' => 'categories',
                'name' => '01J2RRYQAD7AH7220D92SDH9Z6',
                'file_name' => '01JBCHXXTP63H6WH59R7P7V51C.png',
                'mime_type' => 'image/png',
                'disk' => 'aws_categories',
                'conversions_disk' => 'aws_categories',
                'size' => 22381,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-10-29 16:32:18',
                'updated_at' => '2024-10-29 16:32:19',
            ),
            22 => 
            array (
                'id' => 23,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 26,
                'uuid' => '0610c048-14e5-4154-b196-ff7d27654159',
                'collection_name' => 'categories',
                'name' => '01J2RSAZA6PPNG1JDDDFT23A1P',
                'file_name' => '01JBCHYCJN7YQGSZ8MZTC54T8A.png',
                'mime_type' => 'image/png',
                'disk' => 'aws_categories',
                'conversions_disk' => 'aws_categories',
                'size' => 23079,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-10-29 16:32:33',
                'updated_at' => '2024-10-29 16:32:35',
            ),
            23 => 
            array (
                'id' => 24,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 45,
                'uuid' => '43d01d4d-b12b-4cbb-8836-09a1a09b351a',
                'collection_name' => 'categories',
                'name' => 'pngegg-50',
                'file_name' => '01JBCJ0PBND4MR429HZ8PY7JX3.png',
                'mime_type' => 'image/png',
                'disk' => 'aws_categories',
                'conversions_disk' => 'aws_categories',
                'size' => 35322,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-10-29 16:33:48',
                'updated_at' => '2024-10-29 16:33:50',
            ),
        ));
        
        
    }
}