<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MediaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('media')->delete();
        
        \DB::table('media')->insert(array (
            0 => 
            array (
                'id' => 19,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 5,
                'uuid' => '459ddcf3-e076-4c0a-8c19-0d048886045a',
                'collection_name' => 'categories',
                'name' => '01J2RHFD851RWX4CSEH2MMFRFK',
                'file_name' => '01JBCHWMCQZW8BRT6JV6T6ESEX.png',
                'mime_type' => 'image/png',
                'disk' => 's3_categories',
                'conversions_disk' => 's3_categories',
                'size' => 7627,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-10-29 16:31:35',
                'updated_at' => '2024-10-29 16:31:36',
            ),
            1 => 
            array (
                'id' => 20,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 23,
                'uuid' => '0cb68bac-6e61-4d03-980d-80721c2b9bc5',
                'collection_name' => 'categories',
                'name' => '01J2RRTFV5YWAVNS244P356A6W',
                'file_name' => '01JBCHWZ3X5F52M8CGTYPF9NBB.png',
                'mime_type' => 'image/png',
                'disk' => 's3_categories',
                'conversions_disk' => 's3_categories',
                'size' => 47055,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-10-29 16:31:46',
                'updated_at' => '2024-10-29 16:31:48',
            ),
            2 => 
            array (
                'id' => 21,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 24,
                'uuid' => 'bdb2e4b7-64d6-4268-8e32-f52c705cae12',
                'collection_name' => 'categories',
                'name' => '01J2RRZWT3023EW2YSRAN5FDS6',
                'file_name' => '01JBCHXJ7EWQK6M8TZ73RT21XF.png',
                'mime_type' => 'image/png',
                'disk' => 's3_categories',
                'conversions_disk' => 's3_categories',
                'size' => 55450,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-10-29 16:32:06',
                'updated_at' => '2024-10-29 16:32:07',
            ),
            3 => 
            array (
                'id' => 22,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 25,
                'uuid' => 'f89fcda8-0de4-4693-b7b2-24ff579f3676',
                'collection_name' => 'categories',
                'name' => '01J2RRYQAD7AH7220D92SDH9Z6',
                'file_name' => '01JBCHXXTP63H6WH59R7P7V51C.png',
                'mime_type' => 'image/png',
                'disk' => 's3_categories',
                'conversions_disk' => 's3_categories',
                'size' => 22381,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-10-29 16:32:18',
                'updated_at' => '2024-10-29 16:32:19',
            ),
            4 => 
            array (
                'id' => 23,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 26,
                'uuid' => '0610c048-14e5-4154-b196-ff7d27654159',
                'collection_name' => 'categories',
                'name' => '01J2RSAZA6PPNG1JDDDFT23A1P',
                'file_name' => '01JBCHYCJN7YQGSZ8MZTC54T8A.png',
                'mime_type' => 'image/png',
                'disk' => 's3_categories',
                'conversions_disk' => 's3_categories',
                'size' => 23079,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-10-29 16:32:33',
                'updated_at' => '2024-10-29 16:32:35',
            ),
            5 => 
            array (
                'id' => 24,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 45,
                'uuid' => '43d01d4d-b12b-4cbb-8836-09a1a09b351a',
                'collection_name' => 'categories',
                'name' => 'pngegg-50',
                'file_name' => '01JBCJ0PBND4MR429HZ8PY7JX3.png',
                'mime_type' => 'image/png',
                'disk' => 's3_categories',
                'conversions_disk' => 's3_categories',
                'size' => 35322,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-10-29 16:33:48',
                'updated_at' => '2024-10-29 16:33:50',
            ),
            6 => 
            array (
                'id' => 26,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 1,
                'uuid' => '79079ad9-2a9b-4b1c-8439-2f1fb721e0f2',
                'collection_name' => 'categories',
                'name' => '01J5C6C7ZA106E42237PQ6HM5K',
                'file_name' => '01JD5D38N418NBNX3H5MDXNXGH.png',
                'mime_type' => 'image/png',
                'disk' => 's3_categories',
                'conversions_disk' => 's3_categories',
                'size' => 288592,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-11-20 19:24:32',
                'updated_at' => '2024-11-20 19:25:01',
            ),
            7 => 
            array (
                'id' => 27,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 3,
                'uuid' => 'd7c27f95-9d55-419f-a914-b74512312a2c',
                'collection_name' => 'categories',
                'name' => '01J0GTQGGWYW71S48V826Q3BCN',
                'file_name' => '01JD5D5J5RB8CBNSD681ECPPAF.png',
                'mime_type' => 'image/png',
                'disk' => 's3_categories',
                'conversions_disk' => 's3_categories',
                'size' => 49271,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-11-20 19:25:48',
                'updated_at' => '2024-11-20 19:26:01',
            ),
            10 => 
            array (
                'id' => 30,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 4,
                'uuid' => 'b2db9a46-0d00-4dd3-8dc5-50c46e4462e5',
                'collection_name' => 'categories',
                'name' => '01J0M3SG921DXGWXBRDDRMZMYT',
                'file_name' => '01JDAKM0YQAF5Z0V04A52PRT62.png',
                'mime_type' => 'image/png',
                'disk' => 's3_categories',
                'conversions_disk' => 's3_categories',
                'size' => 7504,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-11-22 19:54:45',
                'updated_at' => '2024-11-22 19:54:47',
            ),
            11 => 
            array (
                'id' => 31,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 9,
                'uuid' => '778809e6-96b9-47c0-91ca-7b2265bd2227',
                'collection_name' => 'categories',
                'name' => '01J2RHBVFC38D4XVJ4N6VXHX4T',
                'file_name' => '01JDAKMMZQB74Z88KZM8R00WX4.png',
                'mime_type' => 'image/png',
                'disk' => 's3_categories',
                'conversions_disk' => 's3_categories',
                'size' => 34384,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-11-22 19:55:06',
                'updated_at' => '2024-11-22 19:55:08',
            ),
            12 => 
            array (
                'id' => 32,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 10,
                'uuid' => '8eb6e44b-a7f7-43a6-894c-dac28c869a5b',
                'collection_name' => 'categories',
                'name' => '01J2RH9BE3Q0CPJRY1RJ7TY8YB',
                'file_name' => '01JDAKN923ZTY90F7BCN2YFRBX.png',
                'mime_type' => 'image/png',
                'disk' => 's3_categories',
                'conversions_disk' => 's3_categories',
                'size' => 27003,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-11-22 19:55:26',
                'updated_at' => '2024-11-22 19:55:27',
            ),
            13 => 
            array (
                'id' => 33,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 11,
                'uuid' => '5796703b-4199-4096-a02c-020cd1a6a97f',
                'collection_name' => 'categories',
                'name' => '01J2RJ99PQWSX2T159D2E8T2PN',
                'file_name' => '01JDAKNRQNR8YZ0PH2TS3Q5MH9.png',
                'mime_type' => 'image/png',
                'disk' => 's3_categories',
                'conversions_disk' => 's3_categories',
                'size' => 94509,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-11-22 19:55:42',
                'updated_at' => '2024-11-22 19:55:46',
            ),
            14 => 
            array (
                'id' => 34,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 12,
                'uuid' => '75e499fe-61a0-4bd3-9187-461f1951d2fb',
                'collection_name' => 'categories',
                'name' => '01J2RJKNAPRGDR9403TWYG67E0',
                'file_name' => '01JDAKP955A0ME3CXXNWSN4JD4.png',
                'mime_type' => 'image/png',
                'disk' => 's3_categories',
                'conversions_disk' => 's3_categories',
                'size' => 26578,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-11-22 19:55:59',
                'updated_at' => '2024-11-22 19:56:01',
            ),
            15 => 
            array (
                'id' => 35,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 13,
                'uuid' => '70ed3fc5-24cd-4d58-ae1b-f5d44bba3e37',
                'collection_name' => 'categories',
                'name' => '01J2RJQVTYZCXK1HW2XVCME1JG',
                'file_name' => '01JDAKQ9TAE8SQNC91ZNFWXAAC.png',
                'mime_type' => 'image/png',
                'disk' => 's3_categories',
                'conversions_disk' => 's3_categories',
                'size' => 56308,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-11-22 19:56:33',
                'updated_at' => '2024-11-22 19:56:35',
            ),
            16 => 
            array (
                'id' => 36,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 14,
                'uuid' => '6bc68ea1-60de-46c5-b8c7-4a2109c8f9de',
                'collection_name' => 'categories',
                'name' => '01J2RKYKB8EG7QN7F8Z0N8GMYE',
                'file_name' => '01JDAKQTY63ZY06SYRKXZGS5F3.png',
                'mime_type' => 'image/png',
                'disk' => 's3_categories',
                'conversions_disk' => 's3_categories',
                'size' => 40955,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-11-22 19:56:50',
                'updated_at' => '2024-11-22 19:56:53',
            ),
            17 => 
            array (
                'id' => 37,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 15,
                'uuid' => '34a2b0df-7e07-49e2-910d-47c4f7d06d08',
                'collection_name' => 'categories',
                'name' => '01J0R4S0V5AVA59DA0PFVKCRYB',
                'file_name' => '01JDAKR7EFS2EBFPQPPYNP2S7N.png',
                'mime_type' => 'image/png',
                'disk' => 's3_categories',
                'conversions_disk' => 's3_categories',
                'size' => 57635,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-11-22 19:57:03',
                'updated_at' => '2024-11-22 19:57:06',
            ),
            18 => 
            array (
                'id' => 38,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 16,
                'uuid' => '60de3b9c-2d92-492f-ad65-b7555babda6a',
                'collection_name' => 'categories',
                'name' => '01J2RNDX8CWYVYHVAXZA35CGM5',
                'file_name' => '01JDAKRSDV48Y75XXEV26XHB5P.png',
                'mime_type' => 'image/png',
                'disk' => 's3_categories',
                'conversions_disk' => 's3_categories',
                'size' => 42212,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-11-22 19:57:21',
                'updated_at' => '2024-11-22 19:57:24',
            ),
            19 => 
            array (
                'id' => 39,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 17,
                'uuid' => '21ea4fdb-d3c6-4c38-9a2c-a4fac8f30738',
                'collection_name' => 'categories',
                'name' => '01J2RNGW94VX4JRSBX83EA1HDB',
                'file_name' => '01JDAKSP2QHTYM03NE1Z2KKW1K.png',
                'mime_type' => 'image/png',
                'disk' => 's3_categories',
                'conversions_disk' => 's3_categories',
                'size' => 51733,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-11-22 19:57:51',
                'updated_at' => '2024-11-22 19:57:52',
            ),
            20 => 
            array (
                'id' => 40,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 2,
                'uuid' => '14a0cbe7-6045-4646-a599-f47010b1af1c',
                'collection_name' => 'categories',
                'name' => '01J0H1CJMFJEX6J5VKARXXKG94',
                'file_name' => '01JDAKTDWGXSKQ8M2WMRJ06X96.png',
                'mime_type' => 'image/png',
                'disk' => 's3_categories',
                'conversions_disk' => 's3_categories',
                'size' => 28382,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-11-22 19:58:15',
                'updated_at' => '2024-11-22 19:58:16',
            ),
            21 => 
            array (
                'id' => 41,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 18,
                'uuid' => '5ecc7172-c0f1-4b1a-9d00-a3c510079a94',
                'collection_name' => 'categories',
                'name' => '01J2RNSAJ8KGVZYF3C6G70TXTS',
                'file_name' => '01JDAKTW4TBYPFPXWSDV7T6V3G.png',
                'mime_type' => 'image/png',
                'disk' => 's3_categories',
                'conversions_disk' => 's3_categories',
                'size' => 59157,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-11-22 19:58:30',
                'updated_at' => '2024-11-22 19:58:31',
            ),
            22 => 
            array (
                'id' => 42,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 19,
                'uuid' => '539b8f44-50fc-45b2-84fb-db2463b90a37',
                'collection_name' => 'categories',
                'name' => '—Pngtree—isometric baby room illustrated in_5507109-v1',
                'file_name' => '01JDAMA99AB5GMW48YSTVA0CSW.png',
                'mime_type' => 'image/png',
                'disk' => 's3_categories',
                'conversions_disk' => 's3_categories',
                'size' => 95725,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-11-22 20:06:55',
                'updated_at' => '2024-11-22 20:06:56',
            ),
            23 => 
            array (
                'id' => 43,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 20,
                'uuid' => 'f825b2d4-d6bb-4d21-9735-f5c2aa141aaa',
                'collection_name' => 'categories',
                'name' => '01J2RQ7EY0QHPDX7QABGCRRVG3',
                'file_name' => '01JDAY72BDDA97V6ZMS7YQRBK4.png',
                'mime_type' => 'image/png',
                'disk' => 's3_categories',
                'conversions_disk' => 's3_categories',
                'size' => 28573,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-11-22 22:59:55',
                'updated_at' => '2024-11-22 22:59:58',
            ),
            24 => 
            array (
                'id' => 44,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 21,
                'uuid' => '1c34f281-c2d4-4443-8905-ec3a4310a6b5',
                'collection_name' => 'categories',
                'name' => '01J2RQC369NWHVHCKGZFHPZVTS',
                'file_name' => '01JDAY7KXXM6PNAJH0BWZ1M505.png',
                'mime_type' => 'image/png',
                'disk' => 's3_categories',
                'conversions_disk' => 's3_categories',
                'size' => 20827,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-11-22 23:00:13',
                'updated_at' => '2024-11-22 23:00:14',
            ),
            25 => 
            array (
                'id' => 45,
                'model_type' => 'App\\Models\\Category',
                'model_id' => 22,
                'uuid' => 'c65ed711-1890-4d52-8d63-d7fcf6401710',
                'collection_name' => 'categories',
                'name' => '01J2RQWJREMSCN4J29AQA5VAGE',
                'file_name' => '01JDAY845D31Z9E6YMNXEHJPQH.png',
                'mime_type' => 'image/png',
                'disk' => 's3_categories',
                'conversions_disk' => 's3_categories',
                'size' => 32834,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '{"thumb": true}',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2024-11-22 23:00:30',
                'updated_at' => '2024-11-22 23:00:32',
            ),
        ));
    }
}